os: linux
language: c
sudo: false # only for faster builds
before_install:
  - sudo apt-get update
  - sudo apt-get install -y check
compiler: gcc
script:
  - make
  - make test
  - make test1
  - make test2
  - make test3
  - make test4
